### ISSUE TITLE
JCAuthApplicatioin 실행 오류

### ISSUE THREAD

**Issue by nyeJiiii** [JoberChipFrappuccino/joberchip-be-demo#33]
JCAuthApplicatioin 실행 시 아래와 같은 오류 발생

![image](https://github.com/JoberChipFrappuccino/joberchip-be-demo/assets/128347921/74db90bc-8267-4cb4-9759-267567e7560c)

<br>
- [ ] DB URL 매핑 오류로 보여짐..??

![image](https://github.com/JoberChipFrappuccino/joberchip-be-demo/assets/128347921/56a08e3c-ba5e-4fd8-b418-9d04c824aa9d)

JCServerApplication 은 정상 실행되는데 JCAuthApplication 실행할 때만 이러네요 이거 왜이러죠..

**Comment by nyeJiiii** [comment]
해결!!!

**Comment by gdtknight** [comment]
`application-text.yml` -> `application-test.yml` 파일명 오타 때문에 발생했던거 같습니다 !
